version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.web
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - NETWORK_FOLDER=/app/uploads
      - DOCKER_ENV=1
    volumes:
      - ./uploads:/app/uploads

  worker:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.worker
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - NETWORK_FOLDER=/app/uploads
    volumes:
      - ./uploads:/app/uploads

  redis:
    image: "redis:6.2"
    ports:
      - "6379:6379"