version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/uploads
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A app.main.celery worker --loglevel=info
    volumes:
      - ./uploads:/uploads
    env_file:
      - .env
    depends_on:
      - redis
